/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DisplayPanels;

import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFrame;
import Application.App;
import OPHSAttributes.Trip;

import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JPanel;
import java.awt.CardLayout;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;


/**
 *
 * @author kostos
 */
public class MainFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	final static String instances_path=App.Instances_path;
	final static ArrayList<String> set_names=App.getSetNames();
    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
        this.setSize(1300, 1000);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
        this.setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    @SuppressWarnings("rawtypes")
	private void initComponents() {
{

        jPanel1 = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        SelectionDisplay = new javax.swing.JPanel();
        AInitialDisplay = new javax.swing.JPanel();
        SETSDisplay = new javax.swing.JPanel();
        InstanceComboList = new javax.swing.JComboBox();
        FinishSelection = new javax.swing.JButton();
        SetComboList = new javax.swing.JComboBox();
        SelectMenuDisplay = new javax.swing.JPanel();
        OPHSLabel = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        Select_Button = new javax.swing.JButton();
        Select_Instance = new javax.swing.JButton();
        DisplayPanel = new javax.swing.JPanel();
        Initial = new javax.swing.JPanel();
        GraphPanel = new javax.swing.JPanel();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 850));

        MenuPanel.setBackground(new java.awt.Color(204, 204, 204));
        MenuPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        SelectionDisplay.setBackground(new java.awt.Color(204, 204, 204));
        SelectionDisplay.setLayout(new java.awt.CardLayout());

        AInitialDisplay.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout AInitialDisplayLayout = new javax.swing.GroupLayout(AInitialDisplay);
        AInitialDisplay.setLayout(AInitialDisplayLayout);
        AInitialDisplayLayout.setHorizontalGroup(
            AInitialDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        AInitialDisplayLayout.setVerticalGroup(
            AInitialDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        SelectionDisplay.add(AInitialDisplay, "card2");

        SETSDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        InstanceComboList.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        InstanceComboList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstanceComboListActionPerformed(evt);
            }
        });

        FinishSelection.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        FinishSelection.setText("OK");
        FinishSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishSelectionActionPerformed(evt);
            }
        });

        SetComboList.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        SetComboList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetComboListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SETSDisplayLayout = new javax.swing.GroupLayout(SETSDisplay);
        SETSDisplay.setLayout(SETSDisplayLayout);
        SETSDisplayLayout.setHorizontalGroup(
            SETSDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SETSDisplayLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(FinishSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(SETSDisplayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SETSDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(SetComboList, 0, 150, Short.MAX_VALUE)
                    .addComponent(InstanceComboList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SETSDisplayLayout.setVerticalGroup(
            SETSDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SETSDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SetComboList, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(InstanceComboList, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(FinishSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        SelectionDisplay.add(SETSDisplay, "card3");

        SelectMenuDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        OPHSLabel.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        OPHSLabel.setText("       OPHS-Menu");

        jButton4.setText("jButton3");

        Select_Button.setText("Select Set");

        Select_Instance.setText("Select Instance");
        Select_Instance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select_InstanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SelectMenuDisplayLayout = new javax.swing.GroupLayout(SelectMenuDisplay);
        SelectMenuDisplay.setLayout(SelectMenuDisplayLayout);
        SelectMenuDisplayLayout.setHorizontalGroup(
            SelectMenuDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectMenuDisplayLayout.createSequentialGroup()
                .addGroup(SelectMenuDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectMenuDisplayLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(OPHSLabel))
                    .addGroup(SelectMenuDisplayLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(SelectMenuDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Select_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Select_Instance, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SelectMenuDisplayLayout.setVerticalGroup(
            SelectMenuDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectMenuDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OPHSLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Select_Instance, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Select_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SelectMenuDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SelectionDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SelectMenuDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SelectionDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DisplayPanel.setBackground(new java.awt.Color(255, 255, 255));
        DisplayPanel.setLayout(new java.awt.CardLayout());

        Initial.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout InitialLayout = new javax.swing.GroupLayout(Initial);
        InitialLayout.setHorizontalGroup(
        	InitialLayout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 1008, Short.MAX_VALUE)
        );
        InitialLayout.setVerticalGroup(
        	InitialLayout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 665, Short.MAX_VALUE)
        );
        Initial.setLayout(InitialLayout);

        DisplayPanel.add(Initial, "card3");

        GraphPanel.setBackground(new java.awt.Color(255, 255, 204));
        GraphPanel.setBorder(new LineBorder(new Color(0, 0, 0), 3));

        javax.swing.GroupLayout GraphPanelLayout = new javax.swing.GroupLayout(GraphPanel);
        GraphPanelLayout.setHorizontalGroup(
        	GraphPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 1002, Short.MAX_VALUE)
        );
        GraphPanelLayout.setVerticalGroup(
        	GraphPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 659, Short.MAX_VALUE)
        );
        GraphPanel.setLayout(GraphPanelLayout);

        DisplayPanel.add(GraphPanel, "card3");
        
        OutputPanel = new JPanel();
        OutputPanel.setBorder(new LineBorder(new Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(MenuPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(DisplayPanel, 0, 0, Short.MAX_VALUE)
        				.addComponent(OutputPanel, GroupLayout.PREFERRED_SIZE, 996, Short.MAX_VALUE))
        			.addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(MenuPanel, GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(DisplayPanel, GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(OutputPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)))
        			.addContainerGap())
        );
        OutputPanel.setLayout(new CardLayout(0, 0));
        
        JPanel panel_2 = new JPanel();
        panel_2.setBorder(new LineBorder(new Color(0, 0, 0), 2));
        panel_2.setBackground(Color.LIGHT_GRAY);
        panel_2.setForeground(Color.LIGHT_GRAY);
        
        JButton HotelsOnly = new JButton("Hotels ");
        
        JButton OnlyPOIButton = new JButton("POIs");
        
        JButton RefreshButton = new JButton("Refresh");
        GroupLayout gl_panel_2 = new GroupLayout(panel_2);
        gl_panel_2.setHorizontalGroup(
        	gl_panel_2.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_panel_2.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_panel_2.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(RefreshButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(OnlyPOIButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(HotelsOnly, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addContainerGap(909, Short.MAX_VALUE))
        );
        gl_panel_2.setVerticalGroup(
        	gl_panel_2.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_panel_2.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(HotelsOnly)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(OnlyPOIButton)
        			.addPreferredGap(ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
        			.addComponent(RefreshButton))
        );
        panel_2.setLayout(gl_panel_2);
        
       
        
        First = new JPanel();
        First.setBackground(Color.LIGHT_GRAY);
        OutputPanel.add(First, "name_12525427210193");
        GroupLayout gl_First = new GroupLayout(First);
        gl_First.setHorizontalGroup(
        	gl_First.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 1008, Short.MAX_VALUE)
        );
        gl_First.setVerticalGroup(
        	gl_First.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 93, Short.MAX_VALUE)
        );
        First.setLayout(gl_First);
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 1318, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();}
			Second = new JPanel();
			Second.setBackground(Color.LIGHT_GRAY);
			OutputPanel.add(Second, "name_11387700442636");
			
			Hotels = new JButton("Hotels");
			Hotels.addActionListener(new ActionListener() {
				public void actionPerformed(ActionEvent e) {
					DisplayPanel.remove(GraphPanel);
					GraphPanel=new OnlyHotelMap();
			    	DisplayPanel.add(GraphPanel);
			    	DisplayPanel.repaint();
			    	DisplayPanel.revalidate();
				}
			});
			
			POIs = new JButton("POIs");
			POIs.addActionListener(new ActionListener() {
				public void actionPerformed(ActionEvent e) {
					DisplayPanel.remove(GraphPanel);
					GraphPanel=new OnlyPOIMap();
			    	DisplayPanel.add(GraphPanel);
			    	DisplayPanel.repaint();
			    	DisplayPanel.revalidate();
				}
			});
			
			Refresh = new JButton("Refresh");
			Refresh.addActionListener(new ActionListener() {
				public void actionPerformed(ActionEvent e) {
					DisplayPanel.remove(GraphPanel);
					GraphPanel=new GraphMap();
			    	DisplayPanel.add(GraphPanel);
			    	DisplayPanel.repaint();
			    	DisplayPanel.revalidate();
				}
			});
			
			JButton btnHotelsPathtree = new JButton("Hotels PathTree");
			btnHotelsPathtree.addActionListener(new ActionListener() {
				public void actionPerformed(ActionEvent e) {
					DisplayPanel.remove(GraphPanel);
					GraphPanel=new AllFeasiblePathPanel(0);
			    	DisplayPanel.add(GraphPanel);
			    	DisplayPanel.repaint();
			    	DisplayPanel.revalidate();
				}
			});
			
			button = new JButton("+");
			button.addActionListener(new ActionListener() {
				public void actionPerformed(ActionEvent e) {
					DisplayPanel.remove(GraphPanel);
					if(AllFeasiblePathPanel.getTrip_id_shown()<Trip.getNumber_of_trips()-1){
						AllFeasiblePathPanel.increase();
					}
					GraphPanel=new AllFeasiblePathPanel();
			    	DisplayPanel.add(GraphPanel);
			    	DisplayPanel.repaint();
			    	DisplayPanel.revalidate();
				}
			});
			button.setFont(new Font("Tahoma", Font.BOLD, 12));
			
			button_1 = new JButton("-");
			button_1.addActionListener(new ActionListener() {
				public void actionPerformed(ActionEvent e) {
					DisplayPanel.remove(GraphPanel);
					if(AllFeasiblePathPanel.getTrip_id_shown()>0){
						AllFeasiblePathPanel.decrease();
					}
					GraphPanel=new AllFeasiblePathPanel();
			    	DisplayPanel.add(GraphPanel);
			    	DisplayPanel.repaint();
			    	DisplayPanel.revalidate();
				}
			});
			button_1.setFont(new Font("Tahoma", Font.BOLD, 12));
			GroupLayout gl_Second = new GroupLayout(Second);
			gl_Second.setHorizontalGroup(
				gl_Second.createParallelGroup(Alignment.LEADING)
					.addGroup(gl_Second.createSequentialGroup()
						.addContainerGap()
						.addGroup(gl_Second.createParallelGroup(Alignment.LEADING)
							.addGroup(gl_Second.createSequentialGroup()
								.addComponent(Hotels, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGap(434)
								.addComponent(button_1)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(btnHotelsPathtree)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(button)
								.addGap(186))
							.addGroup(gl_Second.createSequentialGroup()
								.addComponent(POIs, GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
								.addGap(927))
							.addGroup(gl_Second.createSequentialGroup()
								.addComponent(Refresh)
								.addContainerGap(911, Short.MAX_VALUE))))
			);
			gl_Second.setVerticalGroup(
				gl_Second.createParallelGroup(Alignment.LEADING)
					.addGroup(gl_Second.createSequentialGroup()
						.addGroup(gl_Second.createParallelGroup(Alignment.LEADING)
							.addGroup(gl_Second.createSequentialGroup()
								.addGap(6)
								.addComponent(Hotels)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(POIs)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(Refresh))
							.addGroup(gl_Second.createSequentialGroup()
								.addContainerGap()
								.addGroup(gl_Second.createParallelGroup(Alignment.BASELINE)
									.addComponent(btnHotelsPathtree)
									.addComponent(button)
									.addComponent(button_1))))
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
			);
			Second.setLayout(gl_Second);
    }// </editor-fold>                        

    private void Select_InstanceActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    	SetComboList.addItem(" ");
    	for(String set : set_names){
    		SetComboList.addItem(set);
    	}
    	InstanceComboList.removeAll();
        SelectionDisplay.removeAll();
        SelectionDisplay.add(SETSDisplay);
        SelectionDisplay.repaint();
        SelectionDisplay.revalidate();
    }      
    
    private void FinishSelectionActionPerformed(java.awt.event.ActionEvent evt) {                                                
    	String set_value=SetComboList.getSelectedItem().toString();
    	String inst_value=InstanceComboList.getSelectedItem().toString();
    	String final_path=instances_path+"\\"+set_value+"\\"+inst_value;
    	App.RefreshAttributes();
    	App.ReadInstanceData(final_path);
    	DisplayPanel.remove(GraphPanel);
    	GraphPanel=new GraphMap();
    	DisplayPanel.add(GraphPanel);
    	DisplayPanel.repaint();
    	DisplayPanel.revalidate();
        OutputPanel.removeAll();
        OutputPanel.add(Second);
        OutputPanel.repaint();
        OutputPanel.revalidate();

    } 


    private void SetComboListActionPerformed(java.awt.event.ActionEvent evt) {                                             
    	InstanceComboList.removeAllItems();
    	String value=SetComboList.getSelectedItem().toString();
      for(String set : set_names){
    	  if(set.equals(value)){
    		  String set_path=instances_path+"\\"+set;
    		 File set_file=new File(set_path);
    		 ArrayList<String> set_instnaces=App.getInstancesNames(set_file);
    		 for(String inst : set_instnaces){
    			 InstanceComboList.addItem(inst);
    	    	}
    		  break;
    	  }
      }
    }   
    
    private void InstanceComboListActionPerformed(java.awt.event.ActionEvent evt) {                                                  
    
    	
    } 

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify        
    private javax.swing.JPanel GraphPanel;
    private javax.swing.JPanel AInitialDisplay;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JButton FinishSelection;
    private javax.swing.JPanel Initial;
    private javax.swing.JComboBox InstanceComboList;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JLabel OPHSLabel;
    private javax.swing.JPanel SETSDisplay;
    private javax.swing.JPanel SelectMenuDisplay;
    private javax.swing.JButton Select_Button;
    private javax.swing.JButton Select_Instance;
    private javax.swing.JPanel SelectionDisplay;
    private javax.swing.JComboBox SetComboList;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private JPanel OutputPanel;
    private JPanel Second;
    private JButton Hotels;
    private JButton POIs;
    private JButton Refresh;
    private JPanel First;
    private JButton button;
    private JButton button_1;
}
